modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/datapack/vtmon"
logoFile="assets/vtmon/icon.png"
authors="NoSoySun, CarnekVT"
description='''This mod adds almost every CarnekVT's Fakemons and some self-inserts.'''

[[mixins]]
config="vtmon.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="[1.7.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mega_showdown"
type="required"
versionRange="[1.7.3,)"
ordering="AFTER"
side="BOTH"
